### ISSUE TITLE
`test_tail::test_retry9` is failing intermittently

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#3929]
Seen here:
https://github.com/uutils/coreutils/actions/runs/3039076174/jobs/4893584322
```

---- test_tail::test_retry9 stdout ----
current_directory_resolved: 
mkdir: /tmp/.tmp4yrgEi/parent_dir
write(truncate): /tmp/.tmp4yrgEi/parent_dir/watched_file
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils tail -F -s.1 --max-unchanged-stats=1 parent_dir/watched_file
remove: "/tmp/.tmp4yrgEi/parent_dir/watched_file"
rmdir: /tmp/.tmp4yrgEi/parent_dir
mkdir: /tmp/.tmp4yrgEi/parent_dir
write(truncate): /tmp/.tmp4yrgEi/parent_dir/watched_file
remove: "/tmp/.tmp4yrgEi/parent_dir/watched_file"
rmdir: /tmp/.tmp4yrgEi/parent_dir
mkdir: /tmp/.tmp4yrgEi/parent_dir
write(truncate): /tmp/.tmp4yrgEi/parent_dir/watched_file
remove: "/tmp/.tmp4yrgEi/parent_dir/watched_file"
rmdir: /tmp/.tmp4yrgEi/parent_dir
mkdir: /tmp/.tmp4yrgEi/parent_dir
write(truncate): /tmp/.tmp4yrgEi/parent_dir/watched_file
thread 'test_tail::test_retry9' panicked at 'assertion failed: `(left == right)`
  left: `"foo\n"`,
 right: `"foo\nbar\nfoo\nbar\n"`', /home/runner/work/coreutils/coreutils/tests/by-util/test_tail.rs:1552:5


```
