### ISSUE TITLE
`ci`: Fix usage of rust caching to speed up ci runs

### ISSUE THREAD

**Issue by Joining7943** [uutils/coreutils#4741]
Currently, the rust toolchain is installed/updated after the `Swatinem/rust-cache` step.

```yaml
...
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install `rust` toolchain
      run: |
        rustup toolchain install nightly --no-self-update --profile minimal
        rustup default nightly
...
``` 

The order should be reversed to produce cache hits with `rust-cache`:

```yaml
...
    - uses: actions/checkout@v3
    - name: Install `rust` toolchain
      run: |
        rustup toolchain install nightly --no-self-update --profile minimal
        rustup default nightly
    - uses: Swatinem/rust-cache@v2
...
```
