### ISSUE TITLE
"Improving the GNU compatibility" section links in Contributing are broken

### ISSUE THREAD

**Issue by ic3man5** [uutils/coreutils#7201]
All links in this page pointing to `DEVELOPMENT.html` show a 404 page.

https://uutils.github.io/coreutils/docs/contributing.html#improving-the-gnu-compatibility

DEVELOPMENT.html doesn't seem to exist.

**Comment by ic3man5** [comment]
I managed to build the documentation locally and it seems to work okay.

```bash
$ cargo build --features uudoc
$ target/debug/uudoc
$ cargo install mdbook --locked
$ cd docs
$ mdbook serve --open
```

I don't see anywhere that the CI builds this so I'm assuming its manually done? The missing files seem to be from `target/debug/uudoc` not being ran. Can anyone provide some insight here on how the documentation is actually deployed?

**Comment by ic3man5** [comment]
I found this section https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site

It looks like we might require custom steps to build and it would require adminstration setup to make it work successfully.

**Comment by ic3man5** [comment]
Okay I might be able to get CI steps to work on my fork for testing purposes, to be continued...

**Comment by ic3man5** [comment]
Placing this here for now as a placeholder, I can test this later.

`.github/workflows/gh-pages.yml`:
```yaml

name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - run: 
            rustup update stable && rustup default stable
            cargo install mdbook mdbook-toc --locked
            cargo build --release --features "uudoc"
            target/release/uudoc
            mdbook build docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
```
